package com.example.unitconverter.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF006780)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFB7EAFF)
val light_onPrimaryContainer = Color(0xFF001F28)
val light_secondary = Color(0xFF4C626B)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFCFE6F1)
val light_onSecondaryContainer = Color(0xFF071E26)
val light_tertiary = Color(0xFF5A5B7E)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE1E0FF)
val light_onTertiaryContainer = Color(0xFF171837)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFBFCFE)
val light_onBackground = Color(0xFF191C1D)
val light_surface = Color(0xFFFBFCFE)
val light_onSurface = Color(0xFF191C1D)
val light_surfaceVariant = Color(0xFFDBE4E8)
val light_onSurfaceVariant = Color(0xFF40484C)
val light_outline = Color(0xFF70787C)

val dark_primary = Color(0xFF4FD5FF)
val dark_onPrimary = Color(0xFF003543)
val dark_primaryContainer = Color(0xFF004E61)
val dark_onPrimaryContainer = Color(0xFFB7EAFF)
val dark_secondary = Color(0xFFB3CAD4)
val dark_onSecondary = Color(0xFF1E333B)
val dark_secondaryContainer = Color(0xFF344A52)
val dark_onSecondaryContainer = Color(0xFFCFE6F1)
val dark_tertiary = Color(0xFFC3C3EB)
val dark_onTertiary = Color(0xFF2C2E4D)
val dark_tertiaryContainer = Color(0xFF434465)
val dark_onTertiaryContainer = Color(0xFFE1E0FF)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF191C1D)
val dark_onBackground = Color(0xFFE1E3E4)
val dark_surface = Color(0xFF191C1D)
val dark_onSurface = Color(0xFFE1E3E4)
val dark_surfaceVariant = Color(0xFF40484C)
val dark_onSurfaceVariant = Color(0xFFBFC8CC)
val dark_outline = Color(0xFF8A9296)